//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebFive.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExpensesRecord
    {
        public long ExpensesId { get; set; }
        public long ExpensesTypeId { get; set; }
        public System.DateTime ExpensesDate { get; set; }
        public decimal ExpensesAmount { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string ModifiedBy { get; set; }
        public bool IsActive { get; set; }
        public Nullable<long> CompanyId { get; set; }
    
        public virtual CompanyRecord CompanyRecord { get; set; }
        public virtual ExpensesType ExpensesType { get; set; }
    }
}
