//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebFive.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tenant
    {
        public long TenantId { get; set; }
        public string Name { get; set; }
        public string MailAddress { get; set; }
        public string PhoneNumber { get; set; }
        public string MobileNumber { get; set; }
        public string Email { get; set; }
        public Nullable<decimal> LeaseAmount { get; set; }
        public Nullable<System.DateTime> LeaseStartDate { get; set; }
        public Nullable<System.DateTime> LeaseMeturityDate { get; set; }
        public Nullable<System.DateTime> LeaseDueDate { get; set; }
        public string Notes { get; set; }
        public byte[] LeaseAgreement { get; set; }
        public string RentEscalation { get; set; }
        public long PropertyId { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string ModifiedBy { get; set; }
        public bool IsActive { get; set; }
        public string LeaseAgreementFileName { get; set; }
    
        public virtual PropertiesRecord PropertiesRecord { get; set; }
    }
}
