//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebFive.Models.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompanyRecord
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CompanyRecord()
        {
            this.DistributionExpenses = new HashSet<DistributionExpense>();
            this.ExpensesRecords = new HashSet<ExpensesRecord>();
            this.LoanRecords = new HashSet<LoanRecord>();
            this.OwnerCompanyLinks = new HashSet<OwnerCompanyLink>();
            this.PropertiesRecords = new HashSet<PropertiesRecord>();
        }
    
        public long CompanyId { get; set; }
        public string Name { get; set; }
        public string TaxId { get; set; }
        public Nullable<long> ManagingMember { get; set; }
        public byte[] OperatingAgreement { get; set; }
        public byte[] ArticlesOfOrganization { get; set; }
        public Nullable<System.DateTime> DateOfIncorporation { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string ModifiedBy { get; set; }
        public bool IsActive { get; set; }
        public string OperatingAgreementFileName { get; set; }
        public string ArticlesOfOrganizationFileName { get; set; }
    
        public virtual OwnerRecord OwnerRecord { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DistributionExpense> DistributionExpenses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ExpensesRecord> ExpensesRecords { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LoanRecord> LoanRecords { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OwnerCompanyLink> OwnerCompanyLinks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PropertiesRecord> PropertiesRecords { get; set; }
    }
}
