//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebFive.Models.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class DistributionExpense
    {
        public long DistributionExpenseId { get; set; }
        public Nullable<long> CompanyId { get; set; }
        public Nullable<long> OwnerId { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<System.DateTime> DistributionDate { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string ModifiedBy { get; set; }
        public bool IsActive { get; set; }
    
        public virtual CompanyRecord CompanyRecord { get; set; }
        public virtual OwnerRecord OwnerRecord { get; set; }
    }
}
